apiVersion: apps/v1
kind: Deployment
metadata:
  name: skiweb-preview
  labels:
    app: skiweb-preview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skiweb-preview
  template:
    metadata:
      labels:
        app: skiweb-preview
    spec:
      containers:
      - name: skiweb-preview
        image: wthacr.azurecr.io/skiweb:v1.4.10
        env:
        - name: PORT
          value: "3000"        
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: skiweb-service-preview
spec:
  selector:
    app: skiweb-preview
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP        
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: skiweb-ingress-preview
spec:
  tls:
  - hosts:
    - '*.jasondel.com'
    secretName: jasondel-com-tls
  rules:
  - host: skipreview.jasondel.com
    http:
      paths:
      - backend:
          serviceName: skiweb-service-preview
          servicePort: 3000
        path: /