apiVersion: apps/v1
kind: Deployment
metadata:
  name: skiweb
  labels:
    app: skiweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skiweb
  template:
    metadata:
      labels:
        app: skiweb
    spec:
      containers:
      - name: skiweb
        image: gcr.io/jasondel-test-project/skiweb:v1.7.2
        env:
        - name: PORT
          value: "3000"        
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: skiweb-service
spec:
  selector:
    app: skiweb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort        
