apiVersion: apps/v1
kind: Deployment
metadata:
  name: skiweb
  labels:
    app: skiweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skiweb
  template:
    metadata:
      labels:
        app: skiweb
    spec:
      containers:
      - name: skiweb
        image: wthacr.azurecr.io/skiweb:v1.2.2
        env:
        - name: PORT
          value: "3000"        
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: skiweb-service
spec:
  selector:
    app: skiweb
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP        
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: skiweb-ingress
spec:
  tls:
  - hosts:
    - '*.jasondel.com'
    secretName: jasondel-com-tls
  rules:
  - host: ski.jasondel.com
    http:
      paths:
      - backend:
          serviceName: skiweb-service
          servicePort: 3000
        path: /